  name: Build & Deploy Microservices

  on:
    push:
      branches:
        - '*'

  jobs:
    build-deploy:
      name: Build and deploy job
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: 17

        - name: Build and deploy Transaction Log microservice
          if: startsWith(github.ref, 'refs/heads/transaction_log-')
          run: |
            cd transaction_log
            mvn clean
            mvn package
            # Add deployment steps for the Transaction Log microservice

        # Add similar steps for other microservices as needed
